version: '3.2'
services:
  # --------------------------------------------------------------------------
  # SOCS Agents
  # --------------------------------------------------------------------------
  
  # --------------------------------------------------------------------------
  # The Lakeshore 372 Agent
  # --------------------------------------------------------------------------
  ocs-lakeshore372-agent:
    image: "ocs-lakeshore372-agent"
    build: ./agents/lakeshore372/

  # --------------------------------------------------------------------------
  # The Lakeshore 240 Agent
  # --------------------------------------------------------------------------
  ocs-lakeshore240-agent:
    image: "ocs-lakeshore240-agent"
    build: ./agents/lakeshore240/
